import type { Config } from "tailwindcss";

const rgb = (name: string) => `rgb(var(${name}) / <alpha-value>)`;
const token = (name: string) => `var(${name})`;

const config = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "var(--gutter)",
      screens: {
        "2xl": "var(--container-max)",
      },
    },
    extend: {
      colors: {
        border: {
          DEFAULT: rgb("--border-rgb"),
          strong: rgb("--border-strong-rgb"),
          field: rgb("--border-field-rgb"),
          dark: rgb("--border-dark-rgb"),
        },
        input: {
          DEFAULT: rgb("--input-rgb"),
          field: rgb("--border-field-rgb"),
        },
        ring: {
          DEFAULT: rgb("--ring-rgb"),
        },
        background: rgb("--background-rgb"),
        foreground: rgb("--foreground-rgb"),
        popover: {
          DEFAULT: rgb("--popover-rgb"),
          foreground: rgb("--popover-foreground-rgb"),
        },
        primary: {
          DEFAULT: rgb("--primary-rgb"),
          foreground: rgb("--primary-foreground-rgb"),
        },
        secondary: {
          DEFAULT: rgb("--secondary-rgb"),
          foreground: rgb("--secondary-foreground-rgb"),
        },
        muted: {
          DEFAULT: rgb("--muted-rgb"),
          foreground: rgb("--muted-foreground-rgb"),
        },
        accent: {
          DEFAULT: rgb("--accent-rgb"),
          foreground: rgb("--accent-foreground-rgb"),
          soft: token("--accent-soft"),
          strong: rgb("--accent-strong-rgb"),
        },
        destructive: {
          DEFAULT: rgb("--destructive-rgb"),
          foreground: rgb("--destructive-foreground-rgb"),
        },
        card: {
          DEFAULT: rgb("--card-rgb"),
          foreground: rgb("--card-foreground-rgb"),
        },
        ink: {
          900: rgb("--ink-900-rgb"),
          800: rgb("--ink-800-rgb"),
          700: rgb("--ink-700-rgb"),
          600: rgb("--ink-600-rgb"),
          500: rgb("--ink-500-rgb"),
        },
        steel: {
          500: rgb("--steel-500-rgb"),
          400: rgb("--steel-400-rgb"),
          300: rgb("--steel-300-rgb"),
        },
        smoke: {
          400: rgb("--smoke-400-rgb"),
          300: rgb("--smoke-300-rgb"),
          200: rgb("--smoke-200-rgb"),
          100: rgb("--smoke-100-rgb"),
          50: rgb("--smoke-50-rgb"),
        },
        paper: rgb("--paper-rgb"),
        olive: {
          900: rgb("--olive-900-rgb"),
          800: rgb("--olive-800-rgb"),
          700: rgb("--olive-700-rgb"),
          600: rgb("--olive-600-rgb"),
          500: rgb("--olive-500-rgb"),
          400: rgb("--olive-400-rgb"),
          300: rgb("--olive-300-rgb"),
        },
        amber: {
          700: rgb("--amber-700-rgb"),
          600: rgb("--amber-600-rgb"),
          500: rgb("--amber-500-rgb"),
          400: rgb("--amber-400-rgb"),
          300: rgb("--amber-300-rgb"),
        },
        clear: {
          600: rgb("--clear-600-rgb"),
          500: rgb("--clear-500-rgb"),
          400: rgb("--clear-400-rgb"),
          100: rgb("--clear-100-rgb"),
        },
        rust: {
          600: rgb("--rust-600-rgb"),
          500: rgb("--rust-500-rgb"),
          400: rgb("--rust-400-rgb"),
          100: rgb("--rust-100-rgb"),
        },
        hazard: {
          500: rgb("--hazard-500-rgb"),
          100: rgb("--hazard-100-rgb"),
        },
        surface: {
          app: rgb("--bg-app-rgb"),
          card: rgb("--surface-card-rgb"),
          sunken: rgb("--surface-sunken-rgb"),
          raised: rgb("--surface-raised-rgb"),
          inverse: rgb("--surface-inverse-rgb"),
          field: rgb("--surface-field-rgb"),
        },
        content: {
          strong: rgb("--text-strong-rgb"),
          body: rgb("--text-body-rgb"),
          muted: rgb("--text-muted-rgb"),
          faint: rgb("--text-faint-rgb"),
          "on-dark": rgb("--text-on-dark-rgb"),
          "on-olive": rgb("--text-on-olive-rgb"),
          "on-amber": rgb("--text-on-amber-rgb"),
        },
        brand: {
          DEFAULT: rgb("--brand-rgb"),
          strong: rgb("--brand-strong-rgb"),
          hover: rgb("--brand-hover-rgb"),
          soft: token("--brand-soft"),
        },
        fill: {
          olive: token("--fill-olive"),
          amber: token("--fill-amber"),
          green: token("--fill-green"),
          rust: token("--fill-rust"),
          neutral: token("--fill-neutral"),
        },
        soft: {
          olive: rgb("--on-olive-soft-rgb"),
          amber: rgb("--on-amber-soft-rgb"),
          green: rgb("--on-green-soft-rgb"),
          rust: rgb("--on-rust-soft-rgb"),
          neutral: rgb("--on-neutral-soft-rgb"),
        },
        bd: {
          olive: token("--bd-olive"),
          amber: token("--bd-amber"),
          green: token("--bd-green"),
          rust: token("--bd-rust"),
        },
        status: {
          working: rgb("--status-working-rgb"),
          "working-soft": token("--status-working-soft"),
          done: rgb("--status-done-rgb"),
          "done-soft": token("--status-done-soft"),
          attention: rgb("--status-attention-rgb"),
          "attention-soft": token("--status-attention-soft"),
          idle: rgb("--status-idle-rgb"),
          "idle-soft": token("--status-idle-soft"),
        },
      },
      fontFamily: {
        pixel: ["var(--font-pixel)"],
        display: ["var(--font-display)"],
        body: ["var(--font-body)"],
        mono: ["var(--font-mono)"],
        sans: ["var(--font-body)"],
      },
      fontSize: {
        "2xs": ["var(--text-2xs)", { lineHeight: "var(--lh-normal)" }],
        xs: ["var(--text-xs)", { lineHeight: "var(--lh-normal)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--lh-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--lh-normal)" }],
        md: ["var(--text-md)", { lineHeight: "var(--lh-snug)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--lh-snug)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--lh-tight)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--lh-tight)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--lh-tight)" }],
        "4xl": ["var(--text-4xl)", { lineHeight: "var(--lh-tight)" }],
      },
      fontWeight: {
        regular: "var(--fw-regular)",
        medium: "var(--fw-medium)",
        semibold: "var(--fw-semibold)",
        bold: "var(--fw-bold)",
      },
      lineHeight: {
        tight: "var(--lh-tight)",
        snug: "var(--lh-snug)",
        normal: "var(--lh-normal)",
        relaxed: "var(--lh-relaxed)",
      },
      letterSpacing: {
        tight: "var(--ls-tight)",
        normal: "var(--ls-normal)",
        label: "var(--ls-label)",
        wide: "var(--ls-wide)",
      },
      spacing: {
        0: "var(--space-0)",
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        gutter: "var(--gutter)",
        header: "var(--header-h)",
      },
      maxWidth: {
        container: "var(--container-max)",
      },
      borderRadius: {
        DEFAULT: "var(--radius-md)",
        none: "var(--radius-0)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
        full: "var(--radius-pill)",
      },
      borderWidth: {
        hair: "var(--bw-hair)",
        bold: "var(--bw-bold)",
      },
      boxShadow: {
        none: "var(--shadow-none)",
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
      },
      transitionTimingFunction: {
        DEFAULT: "var(--ease-standard)",
        standard: "var(--ease-standard)",
        out: "var(--ease-out)",
      },
      transitionDuration: {
        DEFAULT: "var(--dur-base)",
        fast: "var(--dur-fast)",
        base: "var(--dur-base)",
        slow: "var(--dur-slow)",
      },
      ringOffsetColor: {
        DEFAULT: rgb("--background-rgb"),
        background: rgb("--background-rgb"),
      },
    },
  },
  plugins: [],
} satisfies Config;

export default config;
